### ISSUE TITLE
Backend: Define and extend the schema

### ISSUE THREAD

**Issue by nayeonshin** [codeday-labs/play-request#10]
What types is our API going to have?

**Comment by rohan-bansal** [comment]
Could you elaborate on what you mean by types? I jotted down a few endpoints for a REST api [here](https://www.notion.so/API-Endpoint-Blueprint-63cd7e52de5a46a8b12cbae9b490fa58) and maybe we can morph that into something for graphql.

For the database schema, this is what I was thinking as a general outline:

```
{
    "projects": [
        {
            "id": <id>,
            "name" <name>,
            "contributor_ids": [<github id>, <github id>], // perhaps with github auth supported by firebase
            "timeline_data": <figure out how to store timeline data here>,
            "history": [
                <git tree of changes/commits>
            ],
            "messages": [
                {
                    "id": <id>,
                    "timestamp": <utc timestamp>,
                    "contributor": <github id>,
                    "message": <text>
                }
                ...
            ]
        }
        ...
    ],
    "samples" : [
        {
            "id": <id>
            "name": <name>
            "stored": <reference to storage bucket>
        }
        ...
    ],
    "effects" : [
        {
            "id": <id>
            "name": <name>
            "stored": <reference to storage bucket>
        }
        ...
    ],
}
```

Any additions to this are welcome, this is again just something I thought would work for our current plan.

**Comment by Komal914** [comment]
I think thats a really good starting point Rohan. I'd like to keep it this simple for now until we are ready to add more to the application.

**Comment by nayeonshin** [comment]
@Rohan-Bansal In GraphQL, <code>type</code>'s have fields and these fields return a specific data type.
