### ISSUE TITLE
Frontend: Login Screen 

### ISSUE THREAD

**Issue by nayeonshin** [codeday-labs/play-request#14]
- [ ] User is able to sign up with user and pass
- [ ] User is able to login/log out

**Comment by rohan-bansal** [comment]
This could be a good resource for when we start considering auth (maybe signing in with github/google would be more convenient than email and password): https://firebase.google.com/docs/auth

**Comment by Komal914** [comment]
- [ ] User is able to sign up with user and pass
- [ ] User is able to login/log out
