### ISSUE TITLE
Frontend: Grid

### ISSUE THREAD

**Issue by nayeonshin** [codeday-labs/play-request#15]
For: "Random feature other users' have done displayed for inspo"
- [ ] generate random samples of work from users
- [ ] when user hovers over sample of work, sample is played
- [ ] when user hovers, the box toggles in animation

**Comment by rohan-bansal** [comment]
Where is the grid located? Will it be in the sidebar that contains the samples, messages, etc.?

**Comment by nayeonshin** [comment]
@Rohan-Bansal Pls refer to Komal's miro board. Thanks!
