### ISSUE TITLE
Frontend: Volume slider

### ISSUE THREAD

**Issue by nayeonshin** [codeday-labs/play-request#17]
- [ ] implement a slider for volume
- [ ] add functionality, be able to adjust volume

**Comment by rohan-bansal** [comment]
My suggestion (user story): Volume bar is on toolbar, can be dragged to decrease/increase volume of project. If a waveform is selected on the timeline, the volume bar controls the overall volume of that specific audio.

**Comment by Komal914** [comment]
I like the idea of having a toolbar, we can also move the metronome here as well. For other tools I was thinking we could add bass, speed and options to delete/add sounds.
