### ISSUE TITLE
Frontend: Toggle buttons

### ISSUE THREAD

**Issue by nayeonshin** [codeday-labs/play-request#18]
For things like whether to include the selected part of the uploaded audio in the final version

**Comment by rohan-bansal** [comment]
I'm a bit confused as to what the purpose of the toggle buttons are, could you explain further @nayeonshin ? thanks! 😊

**Comment by nayeonshin** [comment]
@Rohan-Bansal Yea. Say, the user keeps all audio components in the workspace. But if they want to work on the specific ones, they can use toggle some buttons to "mute" the parts that will be worked on later. Hope this makes sense. This is just one example.
