### ISSUE TITLE
Frontend: Metronome

### ISSUE THREAD

**Issue by nayeonshin** [codeday-labs/play-request#19]
Description: A dial (or number controlled by arrows) allows the user to change the tempo. The metronome can be started and stopped by clicking on its icon in the toolbar. //Rohans's description, I just moved it here for convenience (Komal) 
- [ ] Users is able to adjust tempo

**Comment by Rohan-Bansal** [comment]
Description: A dial (or number controlled by arrows) allows the user to change the tempo. The metronome can be started and stopped by clicking on its icon in the toolbar.

**Comment by Komal914** [comment]
- [ ] Users is able to adjust tempo
