### ISSUE TITLE
Frontend: Timeline

### ISSUE THREAD

**Issue by rohan-bansal** [codeday-labs/play-request#20]
A component containing the music being worked on, along with added samples/effects. 
- Idea for separate component (or part of this one): timeline indicator (the draggable bar) to scrub around the music
- [ ] Implement a bar slider 
- [ ] user is able to adjust sound by redo and undo

**Comment by Komal914** [comment]
- [ ] Implement a bar slider 
- [ ] user is able to adjust sound by redo and undo
